name: continuous-delivery

on:
  push:
    branches: [main]

jobs:
  semver-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - uses: ohpensource/generate-version-and-release-notes-gh-action@v2.2.2
        name: semver & changelog
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
          version-prefix: "v"